- name: Terraform init/plan
  # You may pin to the exact commit or the version.
  # uses: comu2e/tfnotify-composite-action@d70aade4cc8468bc8a46f1af1c2263c9d81a0dee
  uses: comu2e/tfnotify-composite-action@1.0.4
  with:
    # Setup terraform
    name: # optional
    - name: Terraform security scan
  # You may pin to the exact commit or the version.
  # uses: triat/terraform-security-scan@759b7cf3d32c770760ffa5ffb68d03276969e5ca
  uses: triat/terraform-security-scan@v3.1.0
  with:
    # Whether or not to comment on pull requests.
    tfsec_actions_comment: # optional, default is true
    # Terraform working directory.
    tfsec_actions_working_dir: # optional, default is .
    # Provide checks via , without space to exclude from run
    tfsec_exclude: # optional
    # Specify the version of tfsec to install
    tfsec_version: # optional
    # The output format: default, json, csv, checkstyle, junit, sarif (check `tfsec` for an extensive list)
    tfsec_output_format: # optional
    # The name of the output file
    tfsec_output_file: # optional
    - name: terraform-plan
  # You may pin to the exact commit or the version.
  # uses: dflook/terraform-plan@50b375f84b6c68c386d78ca53b2af6067eea3d7c
  uses: dflook/terraform-plan@v1.29.1
  with:
    # Path to the terraform configuration
    path: # optional, default is .
    # Name of the terraform workspace
    workspace: # optional, default is default
    # List of backend config values to set, one per line
    backend_config: # optional, default is 
    # Path to a backend config file
    backend_config_file: # optional, default is 
    # Variable definitions
    variables: # optional
    # Comma separated list of vars to set, e.g. 'foo=bar'
    var: # optional
    # List of var file paths, one per line
    var_file: # optional
    # Limit the number of concurrent operations
    parallelism: # optional, default is 0
    # List of resources to target for the plan, one per line
    target: # optional, default is 
    # List of resources to replace if an update is required, one per line
    replace: # optional, default is 
    # A friendly name for this plan
    label: # optional, default is 
    # Add the plan to a GitHub PR
    add_github_comment: # optional, default is true
